<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CustomFactorSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'organization_id' => 1,
                'factor_set_id' => 1,
                'associate_code' => 'CO2-EF-001',
                'factor_link' => 'https://example.com/factor1',
                'data_type' => 'Activity',
                'sub_type' => 'Electricity',
                'unit' => 'kWh',
                'factor_value' => 0.234,
                'ch4' => 0.0,
                'n2o' => 0.0,
                'co2' => 0.234,
                'co2_biogenic' => null,
                'ghg_total' => 0.234,
                'ghg_units' => 'kg CO2e',
                'source' => 'Defra 2022',
                'source_category' => 'Energy',
                'scope' => 'Scope 2',
                'activity_id' => 'ACT001',
                'activity_name' => 'Electricity Consumption',
                'fuel_id' => null,
                'fuel_name' => null,
                'region_name' => 'UK',
                'region_code' => 'GB',
                'region_id' => null,
                'country' => 'United Kingdom',
                'state' => null,
                'city' => null,
                'effective_date' => '2022-01-01',
                'published_date' => '2022-06-01',
                'description' => 'Electricity emission factor UK 2022',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organization_id' => 1,
                'factor_set_id' => 1,
                'associate_code' => 'CO2-EF-002',
                'factor_link' => 'https://example.com/factor2',
                'data_type' => 'Fuel',
                'sub_type' => 'Diesel',
                'unit' => 'liters',
                'factor_value' => 2.68,
                'ch4' => 0.0001,
                'n2o' => 0.0002,
                'co2' => 2.6797,
                'co2_biogenic' => null,
                'ghg_total' => 2.68,
                'ghg_units' => 'kg CO2e',
                'source' => 'IPCC 2021',
                'source_category' => 'Transport',
                'scope' => 'Scope 1',
                'activity_id' => 'ACT002',
                'activity_name' => 'Diesel Combustion',
                'fuel_id' => 'FUEL001',
                'fuel_name' => 'Diesel',
                'region_name' => 'Indonesia',
                'region_code' => 'ID',
                'region_id' => null,
                'country' => 'Indonesia',
                'state' => 'Jawa Barat',
                'city' => 'Bandung',
                'effective_date' => '2023-01-01',
                'published_date' => '2023-02-01',
                'description' => 'Diesel combustion factor Indonesia 2023',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organization_id' => 1,
                'factor_set_id' => 1,
                'associate_code' => 'CO2-EF-003',
                'factor_link' => 'https://example.com/factor3',
                'data_type' => 'Fuel',
                'sub_type' => 'Petrol',
                'unit' => 'liters',
                'factor_value' => 2.31,
                'ch4' => 0.00005,
                'n2o' => 0.0001,
                'co2' => 2.30985,
                'co2_biogenic' => null,
                'ghg_total' => 2.31,
                'ghg_units' => 'kg CO2e',
                'source' => 'IPCC 2021',
                'source_category' => 'Transport',
                'scope' => 'Scope 1',
                'activity_id' => 'ACT003',
                'activity_name' => 'Petrol Combustion',
                'fuel_id' => 'FUEL002',
                'fuel_name' => 'Petrol',
                'region_name' => 'Indonesia',
                'region_code' => 'ID',
                'region_id' => null,
                'country' => 'Indonesia',
                'state' => 'DKI Jakarta',
                'city' => 'Jakarta',
                'effective_date' => '2023-01-01',
                'published_date' => '2023-03-01',
                'description' => 'Petrol combustion factor Indonesia 2023',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 7 data dummy tambahan (CO2-EF-004 hingga CO2-EF-010)
        ];

        // Tambahan 7 baris dummy sisanya
        for ($i = 4; $i <= 10; $i++) {
            $data[] = [
                'organization_id' => 1,
                'factor_set_id' => 1,
                'associate_code' => "CO2-EF-00$i",
                'factor_link' => "https://example.com/factor$i",
                'data_type' => 'Fuel',
                'sub_type' => 'Dummy Type',
                'unit' => 'unit',
                'factor_value' => 1.23 + $i,
                'ch4' => 0.001 * $i,
                'n2o' => 0.002 * $i,
                'co2' => 1.22 + $i,
                'co2_biogenic' => null,
                'ghg_total' => 1.23 + $i,
                'ghg_units' => 'kg CO2e',
                'source' => "Dummy Source $i",
                'source_category' => "Category $i",
                'scope' => 'Scope 1',
                'activity_id' => "ACT00$i",
                'activity_name' => "Activity $i",
                'fuel_id' => "FUEL00$i",
                'fuel_name' => "Fuel $i",
                'region_name' => 'Region',
                'region_code' => 'RG',
                'region_id' => null,
                'country' => 'Dummyland',
                'state' => 'State X',
                'city' => "City $i",
                'effective_date' => '2024-01-01',
                'published_date' => '2024-02-01',
                'description' => "Dummy description $i",
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('custom_factors')->insert($data);
    }
}
