<?php

return [
    'envizi' => [
        'api_address' => [
            'au_apac'=>[
                'url' =>'https://auapi.envizi.com/api/meta/', 
            ],
            'us_apac'=>[
                'url' =>'https://usapi.envizi.com/api/meta/', 
            ],
            'us'=>[
                'url' =>'https://usapi.envizi.com/api/meta/', 
            ],
            'uk'=>[
                'url' =>'https://ukapi.envizi.com/api/meta/', 
            ],
            'euro'=>[
                'url' =>'https://euapi.envizi.com/api/meta/', 
            ],
            'midle_east'=>[
                'url' =>'https://meapi.envizi.com/api/meta/', 
            ],
        ],
        'api_token_asri' =>'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIzYjZhNjYwLTYxOGEtNDMzOS1hNTNiLTZhMDE3Njc5NTliNSIsIm5hbWUiOiJha2l0LmZpcmRhdXNAZ21haWwuY29tIiwic3ViIjoiMTcwMDc3NzciLCJlbWFpbCI6ImFraXQuZmlyZGF1c0BnbWFpbC5jb20iLCJqdGkiOiIxN2ExMTlhNi0yOTlkLTQxNTEtOWUzZi03YmNlOGRhOWI0YTgiLCJzY29wZSI6WyJhcGk6bWV0YTpyZWFkIiwiYXBpOnJlcG9ydDpyZWFkIl0sIm5iZiI6MTc0ODQwMTc5OSwiZXhwIjoyMTQ3NDcyMDAwLCJpYXQiOjE3NDgzOTA0MDAsImlzcyI6ImVudml6aS5jb20iLCJhdWQiOiJhcGkuZW52aXppLmNvbSJ9.4uWauD8PrFgqT7HbkwFDYo9wBWfdk4Ub8kOB5oz8R6_GUFfTsPd_eiWu0picHiUljJdI3ZpcVpCA_HUenKNcOA',
        'api_token_buma' => "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmY2IyZmQ5LTBlMzUtNGYwMi05NTkxLTg1ZmIyNzZkYTRmMCIsIm5hbWUiOiJoYXJ0YUBkZWx0YWR1bmlhLmNvbSIsInN1YiI6IjE3MDA0NDQwIiwiZW1haWwiOiJoYXJ0YUBhZ2lsZS5jby5pZCIsImp0aSI6IjdmMmY0MzFkLTEzZjQtNDUyYS05ZmM5LTE4NzgxZGE3OWZjYiIsInNjb3BlIjpbImFwaTptZXRhOnJlYWQiLCJhcGk6cmVwb3J0OnJlYWQiXSwibmJmIjoxNzE3NDI4OTM0LCJleHAiOjIxNDc0NzIwMDAsImlhdCI6MTcxNzM3MjgwMCwiaXNzIjoiZW52aXppLmNvbSIsImF1ZCI6ImFwaS5lbnZpemkuY29tIn0.zRYbvaPmxJ1OoUfU_I0p5X3ZbvbzacSWHoYvprKwySIf5a32wr1FocLjdDmS90kEidLKwoYd-8hGaeCWg-YGww",
        'api_token_agile_poc' => 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMmM4YmE4LWJhYzctNGRkOC1iYjJkLWM4MzY4Mzc3MmE3MSIsIm5hbWUiOiJoYXJ0YUBhZ2lsZS5jby5pZCIsInN1YiI6IjE3MDAyNTg1IiwiZW1haWwiOiJoYXJ0YUBhZ2lsZS5jby5pZCIsImp0aSI6ImE3MmU2NGJlLTEwMDUtNDNjNC05Nzc4LTc4YTJjNzI2ZTY2ZCIsInNjb3BlIjpbImFwaTptZXRhOnJlYWQiLCJhcGk6cmVwb3J0OnJlYWQiXSwibmJmIjoxNzE5NzA2MzY1LCJleHAiOjIxNDc0NzIwMDAsImlhdCI6MTcxOTcwNTYwMCwiaXNzIjoiZW52aXppLmNvbSIsImF1ZCI6ImFwaS5lbnZpemkuY29tIn0.2tbOcxI5aK-W_jdrSdk74CJH8RX7_f81uBHN_YgcVWna-55r63kbfo4DEDRD9R1ouWTCRdvySC4RVvqFC4Czvg',
        's3_asri' =>'client_82ef41b0d5e44a/',
        's3_folder_buma' =>"client_209a3264c7744b/", 
        's3_folder_agile_poc' =>"client_da5d7a6ba0ff4b/", 
        'file_name' => "POCAccountSetupandDataLoad_mid.xlsx",
        'file_name_csr' => "Account_Setup_and_Data_Load_CSR_mid.xlsx",
        'reports' => [
            'AccountItemsAndCostAudit' => "_Envizi-AccountItemsAndCostAudit",   
            'AccountItemsAudit' => "_Envizi-AccountItemsAudit",
            "AccountsDataVarianceExceptions"=>"_Envizi-AccountsDataVarianceExceptions",
            "AccountStyleDataExtract"=>"_Envizi-AccountStyleDataExtract",
            "BillCheckingMissingandOverlapping"=>"_Envizi-BillCheckingMissingandOverlapping",
            "BillCheckingVarianceAndMeterComparison"=>"_Envizi-BillCheckingVarianceAndMeterComparison",
            "ClassificationGroupVerification"=> "_Envizi-ClassificationGroupVerification",
            "DashboardUsageAudit"=>"_Envizi-DashboardUsageAudit",
            "DataCompletenessUsingClosedOnDates"=>"_Envizi-DataCompletenessUsingClosedOnDates",
            "DataCompletenessUsingOpenedOnDates"=>"_Envizi-DataCompletenessUsingOpenedOnDates",
            "EnergyStarRatings"=>"_Envizi-EnergyStarRatings",
            "ExportSurveyResponses"=>"_Envizi-ExportSurveyResponses",
            "ExtractForAccounts"=>"_Envizi-ExtractForAccounts",
            "ExtractForContacts"=>"_Envizi-ExtractForContacts",
            "ExtractForLocations"=>"_Envizi-ExtractForLocations",
            "ExtractForLocationWeatherData"=>"_Envizi-ExtractForLocationWeatherData",
            "ExtractForSurveyResponsesAndAttributes"=>"_Envizi-ExtractForSurveyResponsesAndAttributes",
            "IssueDetailsCBA"=>"_Envizi-IssueDetailsCBA",
            "LocationMonthlyDataCurrentandPreviousYear"=>"_Envizi-LocationMonthlyDataCurrentandPreviousYear",
            "Locations_GetViewable"=>"_Envizi-Locations_GetViewable",
            "LocationsDetails"=>"_Envizi-LocationsDetails",
            "MarketBasedEmissions"=>"_Envizi-MarketBasedEmissions",
            "MissingDataDateRange"=>"_Envizi-MissingDataDateRange",
            "MonthlyActualvsExpectedWeatherNormalize"=>"_Envizi-MonthlyActualvsExpectedWeatherNormalize",
            "MonthlyDataSummary"=>"_Envizi-MonthlyDataSummary",
            "MonthlyDataSummary_CDP"=>"_Envizi-MonthlyDataSummary_CDP",
            "MonthlyDataSummaryAllMeasures"=>"_Envizi-MonthlyDataSummaryAllMeasures",
            "NGERsActivityDatabyState-EERS"=>"_Envizi-NGERsActivityDatabyState-EERS",
            "PBIEmbeddedCache"=>"_Envizi-PBIEmbeddedCache",
            "RawDataExtract"=>"_Envizi-RawDataExtract",
            "RecentLogins"=>"_Envizi-RecentLogins",
            "RecordsAndCostAudit"=>"_Envizi-RecordsAndCostAudit",
            "ReportUsageDetails"=>"_Envizi-ReportUsageDetails",
            "SetupAccounts"=>"_Envizi-SetupAccounts",
            "SetupGroups"=>"_Envizi-SetupGroups",
            "SetupIssues"=>"_Envizi-SetupIssues",
            "SetupLocationRatings"=>"_Envizi-SetupLocationRatings",
            "SetupLocations"=>"_Envizi-SetupLocations",
            "SetupMeterAlertRules"=>"_Envizi-SetupMeterAlertRules",
            "SetupMeters"=>"_Envizi-SetupMeters",
            "SetupTariffs"=>"_Envizi-SetupTariffs",
            "WeatherStationReview"=>"_Envizi-WeatherStationReview",
            "IssueDetails"=>"_Envizi-IssueDetails",
            "EquipmentMonthlyMetrics"=>"_Envizi-EquipmentMonthlyMetrics",
            "IssueSummary"=>"_Envizi-IssueSummary",
            "GRESBExtractforLocationRatings"=>"_Envizi-GRESBExtractforLocationRatings",
            "MonthlyDataSummary_GRESB"=>"_Envizi-MonthlyDataSummary_GRESB",
            "ElectricityIntervalDataExtract"=>"_Envizi-ElectricityIntervalDataExtract",
            "NABERSIndicativeRatingsbyLocation"=>"_Envizi-NABERSIndicativeRatingsbyLocation",
            "NABERSIndicativeRatingsGeneration"=>"_Envizi-NABERSIndicativeRatingsGeneration",
            "ExtractforPrograms"=>"_Envizi-ExtractforPrograms",
            "ExtractForLocations-Solar"=>"_Envizi-ExtractForLocations-Solar",
            "SolarPerformanceAndPayback"=>"_Envizi-SolarPerformanceAndPayback",
            "ActualvsTargetandBudget"=>"_Envizi-ActualvsTargetandBudget",
            "SetupTargetData"=> "_Envizi-SetupTargetData",
        ],
        'cloud' => [
            'state' => true,
            'url' => 'http://apps.agile.co.id/obpos/public/api/amanda',
            'uid' => 'pelni',
            'pin' => '24453',
            'method' => [
                'cek_server' => 'cek.server',
                'save_amanda' => 'save.amanda',
                'save_official_memos' => 'save.official.memos',
                'save_sales' => 'save.sales',
            ]
        ],
        'independent' => [
            'state' => true,
            'url' => 'http://192.168.7.1/obpos/public/api/',
            'uid' => 'pelni',
            'pin' => '870939',
            'method' => [
                'cek_ip' => 'rajabiller.cekip',
                'cek_saldo' => 'rajabiller.balance',
                'cek_harga' => 'rajabiller.harga',
                'cek_info_produk' => 'rajabiller.info_produk',
                'topup_pulsa' => 'rajabiller.pulsa',
                'topup_game' => 'rajabiller.game',
                'inquiry' => 'rajabiller.inq',
                'payment' => 'rajabiller.pay',
                'inquiry_bpjs' => 'rajabiller.bpjsinq',
                'payment_bpjs' => 'rajabiller.bpjspay',
                'data_transaksi' => 'rajabiller.datatransaksi',
                'cetak_ulang' => 'rajabiller.cu',
                'cetak_ulang_detail' => 'rajabiller.cudetail',
                'inquiry_pln' => 'rajabiller.inqpln',
                'payment_pln' => 'rajabiller.paypln',
                'group_produk' => "rajabiller.group_produk",
            ]
        ],
    ],
];

 